### ISSUE TITLE
Should this not be AWS_ACCESS_KEY_ID?

### ISSUE THREAD

**Issue by ViktorHaag** [BrightspaceUI/documentation#45]
https://github.com/BrightspaceUI/documentation/blob/ab2298e6f28edfd7d3263161fde858b42d669a48/.travis.yml#L16

Amazon's docs for the boto3 (python) client's credentials say that the ENV variable name for the access key ID should be `AWS_ACCESS_KEY_ID`... (see http://boto3.readthedocs.io/en/latest/guide/configuration.html#environment-variables)

Is this just a difference between the Python and JS libraries? (Seems weird if so?)

**Comment by dlockhart** [comment]
So we're not actually using [Travis CI's automatic S3 deployment](https://docs.travis-ci.com/user/deployment/s3/) because I wanted to customize too much about how things get deployed -- custom headers for caching, etc.

Instead, we're using the S3 NPM module, which we just [pass the access key to as an ENV variable](https://github.com/BrightspaceUI/documentation/blob/master/_publisher/publisher.js#L23).

**Comment by ViktorHaag** [comment]
Ah! I get it. You're using "the wrong" env var name, but it doesn't matter because you're passing on its value in your gluecode. Makes sense.

In our case, Boto3 is going (supposed to be able) to read the value either directly from the ENV in a var name it knows about, or from an identified profile if used on a desktop and not in Travis.
